🌟 Why NumPy Is Faster Than Python Lists

NumPy is built on a powerful core structure called the ndarray (N-Dimensional Array).
Understanding this explains why NumPy is much faster than Python lists.

🔷 1. Python List vs NumPy ndarray
❌ Python List (Slow)

List elements can be different data types.

Each element has its own separate memory pointer.

Memory is scattered, not continuous.

CPU must jump around memory, making access slow.

Example problem:

[5, "hello", 10.5, True]


Each item:

Different size

Different data type

Stored in different memory locations



🔷 2. NumPy ndarray (Fast)
✔ Same Data Type

All elements must be of the same type (all int, all float, etc.).

✔ Continuous Memory Block

Data is stored in one continuous block in RAM.

This results in:

Faster memory access

Faster computation

Better performance in loops and math operations

✔ Quick Comparison
Feature	Python List	NumPy ndarray
Data Types	Mixed	Same
Memory Layout	Scattered	Continuous
Speed	Slow	Fast



🔷 3. Vectorization = Huge Speed Boost

NumPy does operations on entire arrays at once, not one-by-one.

Example:

a = np.array([1, 2, 3, 4])

a * 2


NumPy applies multiplication to the whole array using one optimized instruction.



🔷 4. CPU Optimization: SIMD

Modern CPUs support SIMD (Single Instruction Multiple Data).

🧠 SIMD means:

CPU loads multiple values at the same time

Performs the same operation on them in parallel

Greatly improves performance

✔ NumPy ndarray

Works perfectly with SIMD because memory is continuous.

❌ Python list

CPU must load each element one at a time → slow.





✅ Final Summary

NumPy is fast because of the ndarray structure.

ndarray uses same data type + continuous memory.

Enables vectorized computation.

CPU uses SIMD parallel processing.

Python lists cannot do this → slower performance.

In [ ]:
a = [1,2,3]
print(a*5)

b = [x*5 for x in a]
print(b)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]
[5, 10, 15]


In [ ]:
import numpy as np

#np.array(any iterable pass kora jabe)

a = np.array([1,2,3])
b = a*5
print(b)

print(a.ndim)

# 2D array

arr2 = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr2.ndim)


# 3D array

arr3 = np.array(
    [
      # 1st floor
       [[1,2,3],
    [4,5,6]],

      # 2nd floor
      [[1,2,3],
    [4,5,6]],

      # 3rd floor
      [[1,2,3],
    [4,5,6]]

    ]
)

print(arr3.ndim)


[ 5 10 15]
1
2
3


In [ ]:
# Array attribute

# dimension
print(arr3.ndim)

#shape
print(arr3.shape) # number of floor -> number of row on each floor -> number of column on each floor

#data type
print(arr3.dtype)

#Size
print(arr3.size) # number of individual element


3
(3, 2, 3)
int64
18


# Upcasting

In [ ]:
# upcasting into float


double_precision_float_value = np.array([1,1.5,1.7])
# ekta float thakleo baki gulakeo float e convert kore nibe upcasting
print(double_precision_float_value.dtype)


# upcasting into string
arr = np.array([1,2,3.2,'3'])
print(arr.dtype)
print(arr)



float64
<U32
['1' '2' '3.2' '3']


# Selecting a data type for an array

In [ ]:
arr = np.array([1,2,3] , dtype= np.int8)

print(arr.dtype)

# issue
# int8 range from -128 to 127


arr = np.array([1,2,3,300] , dtype=np.int8) # this will show a error


int8


OverflowError: Python integer 300 out of bounds for int8

In [ ]:
arr = np.array([1,2,3.2,'Mahio'] , dtype = np.float64)
# we can't convert a string into a float

ValueError: could not convert string to float: 'Mahio'

In [ ]:
arr = np.array([1,2,3.2,'45'] , dtype = np.float64)
print(arr)

[ 1.   2.   3.2 45. ]


In [ ]:
# Convert data type using "arr.astype"

arr = np.array([1,2,3,4,5])
print(arr.dtype)

arr.astype(np.int16) # Store kora lage

arr = arr.astype(np.int16)
print(arr.dtype)

int64
int64


In [ ]:
# Convert data type using "arr.astype"

arr = np.array([1,2,3,4,5])
print(arr.dtype)

arr = arr.astype(np.int16)   # store the converted array
print(arr.dtype)


int64
int16


# ndarray from existing data type

### From List

In [ ]:
# From List

li = [1,2,3,4,5]
arr= np.array(li)

print(arr.dtype)

mixed_list = [1,2,3,'hello' , True]
arr=np.array(mixed_list)

print(arr)
print(arr.dtype) # Unicode 32


int64
['1' '2' '3' 'hello' 'True']
<U21


In [ ]:
# if a mixed list with another list that can't be possible

mixed_list = [1,2,3,'hello' , True ,[1,2,3]]
arr=np.array(mixed_list)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (6,) + inhomogeneous part.

In [ ]:
matrix = [
    [1,2,3],
    [4,5,6]
]

arr = np.array(matrix)

print(type(arr))
print(arr.dtype)
print(arr.shape) # Row column
print(arr.ndim)


<class 'numpy.ndarray'>
int64
(2, 3)
2


### From Tuple

In [ ]:
# From Tuple

tuple = (1,2,34)
arr = np.array(tuple)


print(type(arr))
print(arr.dtype)
print(arr.shape) # Row column ( But this case just column )
print(arr.ndim)

arr = arr.astype(np.int16)
print(arr.dtype)

<class 'numpy.ndarray'>
int64
(3,)
1
int16


### Set and Dictionary te list a convert kore nite hobe

### From Set ( It's take full set as a object )

That's why we need to convert the set into list first then into ndarray

In [ ]:
st = {1,2,3}

arr= np.array(st)
print(arr)
print(arr.dtype)

{1, 2, 3}
object


In [ ]:
# solution
arr= np.array(list(st))
print(arr)
print(arr.dtype)

[1 2 3]
int64


### From Dictionary

In [ ]:
dic = {'a' : 20 ,
       'b' : 30,
       'c' : 40}

keys = dic.keys()
print(keys)
values = dic.values()
items = dic.items()


dict_keys(['a', 'b', 'c'])


In [ ]:
# Covert keys into ndarray

# list a convert kore nite hobe

arr = np.array(list(keys))

print(arr)
print(type(arr))
print(arr.dtype)  # U1 ( 1 means maximun length 1 )
print(arr.shape) # Row column ( But this case just column )
print(arr.ndim)
print(arr.size) # number of element


['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [ ]:
# Covert values into ndarray

# list a convert kore nite hobe must (set+dic)

arr = np.array(list(values))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape) # Row column ( But this case just column )
print(arr.ndim)
print(arr.size) # number of element

[20 30 40]
<class 'numpy.ndarray'>
int64
(3,)
1
3


In [ ]:
# Covert items into ndarray

# list a convert kore nite hobe must (set+dic)

arr = np.array(list(items))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape) # Row column
print(arr.ndim)
print(arr.size) # number of element

[['a' '20']
 ['b' '30']
 ['c' '40']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


# Creating ndarray form scratch

In [ ]:
import numpy as np

arr = np.zeros((3)) # 1D
print(arr)

arr = np.zeros((1,3)) # 2D
print(arr)

arr = np.zeros((1,1,3)) # floor row column 3D
print(arr)

arr = np.zeros((1,3) ,dtype=np.int8)
print(arr.dtype)





# onno ekta array er moto kore banaite chaile

arr3 = np.array(
    [
      # 1st floor
       [[1,2,3],
    [4,5,6]],

      # 2nd floor
      [[1,2,3],
    [4,5,6]],

      # 3rd floor
      [[1,2,3],
    [4,5,6]]

    ]
)

print(arr3.ndim)

arr = np.zeros_like(arr3)

print(arr.ndim)
print(arr)

[0. 0. 0.]
[[0. 0. 0.]]
[[[0. 0. 0.]]]
int8
3
3
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [ ]:
# np.ones  or  np.ones_like

arr = np.ones((3,4))
print(arr)

print(".."*40)

arr = np.ones_like(arr3)
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
................................................................................
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [ ]:
# np.empty

# random kichu value diye fill thake kokhono kokhono

arr = np.empty((4,3) , dtype=np.int8)
print(arr)

print("=="*80)

arr = np.empty_like(arr3)
print(arr)

[[-58  94  74]
 [ 59   0   0]
 [  0   0   0]
 [  0   0   0]]
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [ ]:
# np.full

# Create matrix with any value

arr = np.full((4,3) , 9)
print(arr)

print("=="*40)

arr = np.full((4,3) , 45)
print(arr)

print("=="*40)

# fill with infinity
arr= np.full((4,3) , np.inf)

print(arr.dtype) # This is a float so if i use (fill_like) that time we need to careful about the type

print(arr)

print("=="*40)

# jamela

# like diye banale data type ta hobe arr3 er moto sekhane ami 10.5, 12 ,19.0 ja icca dei na keno

arr = np.full_like(arr3 , 10.5) # hoye jabe integer
print(arr)
print("=="*40)

arr = np.full_like(arr3 , np.inf)
print(arr)
print("=="*40)

# Solve
arr = np.full_like(arr3, np.inf , dtype=np.float64)
print(arr)


[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]
[[45 45 45]
 [45 45 45]
 [45 45 45]
 [45 45 45]]
float64
[[inf inf inf]
 [inf inf inf]
 [inf inf inf]
 [inf inf inf]]
[[[10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]]]
[[[-9223372036854775808 -9223372036854775808 -9223372036854775808]
  [-9223372036854775808 -9223372036854775808 -9223372036854775808]]

 [[-9223372036854775808 -9223372036854775808 -9223372036854775808]
  [-9223372036854775808 -9223372036854775808 -9223372036854775808]]

 [[-9223372036854775808 -9223372036854775808 -9223372036854775808]
  [-9223372036854775808 -9223372036854775808 -9223372036854775808]]]
[[[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]

 [[inf inf inf]
  [inf inf inf]]]


/usr/local/lib/python3.12/dist-packages/numpy/_core/numeric.py:452: RuntimeWarning: invalid value encountered in cast
  multiarray.copyto(res, fill_value, casting='unsafe')


# Random range Numpy array generation

In [ ]:
arr = np.random.rand(2,4)  # eikkhetre size ar tuple akare deya lagbe na ( 0 to 1 er moddhe equally distrubuted random number )

print(arr)

[[0.77085687 0.86802491 0.62802964 0.37719627]
 [0.75390727 0.78355242 0.41661772 0.14458635]]


In [ ]:
# random integer in range

# random number nijer mon moto nite chaile

# np.random.ranint(start ,end, tuple_shape)

arr = np.random.randint(1,10,(2,5))

print(arr)

[[9 3 1 2 5]
 [1 7 7 9 5]]


In [ ]:
# floating value in a range

# np.random.uniform(start , end , tuple_shape)

arr = np.random.uniform(1,100,(2,3))
print(arr)

[[21.85957604 27.68273791 83.30034815]
 [54.7222344  88.57923624 97.77320568]]


# ndaray creation with range funtion ( oi range e sob gula value i thakbe )

In [ ]:
# as like for in range(start , end, step)
import numpy as np

arr = np.arange(1,10,1)

# shape deyar age ebar consider kore nite hoeb range er moddhe koyta value ache seigula diye row column koyta create kora jave
print(arr)

print("=="*40)

arr = np.arange(1,10,1).reshape(3,3)
print(arr)

arr = np.arange(1,5,1).reshape(3,3)
print(arr)



[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


ValueError: cannot reshape array of size 4 into shape (3,3)

In [ ]:
arr = np.arange(1,10,1)

# another
matrix = arr.reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Linear space
# jotovag e vag korte bolbo totota vage range ta ke vag kore dibe

# np.linspace(start , end(include) , number_of_points)

arr = np.linspace(1,10,10)
print(arr)

arr = np.linspace(1,9,11)

# prottekta point theke prottekta point er distance same

print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1.  1.8 2.6 3.4 4.2 5.  5.8 6.6 7.4 8.2 9. ]


In [ ]:
# np.logspace (start , end(include) , number_of_points)

# here start end mainly define the power ki ki hobe eitar basis e ekhon se base  fix korbe

arr = np.logspace(0,4,5)
print(arr)

print("=="*40)

arr = np.logspace(0,4,10)
print(arr)

print("=="*40)


# if we want we can fix the base

arr = np.logspace(0,4,5,base=2)
print(arr)

arr = np.logspace(0,4,5,base=10)
print(arr)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
[1.00000000e+00 2.78255940e+00 7.74263683e+00 2.15443469e+01
 5.99484250e+01 1.66810054e+02 4.64158883e+02 1.29154967e+03
 3.59381366e+03 1.00000000e+04]
[ 1.  2.  4.  8. 16.]
[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]


# Diagonal --> primary , secondary diagonal

In [ ]:
dia = np.diag([1,2,3])

print(dia)

print("=="*40)

dia = np.diag([1,2,3,4])

print(dia)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# Indentity Matrix

In [ ]:
eye = np.eye(3)

print(eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# np.eye(row , column)

# row column alada value hole row*row projonto primary diagonal thakeb bakita as usual zero

arr = np.eye(3,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [ ]:
# np.eye(row , column , k)

# Diagonal sorate chaile

arr = np.eye(3,4 ,-1) # -1 mani ek ghor nicher dike chole asbe
print(arr)

print("=="*40)
arr = np.eye(3,4 ,-2)
print(arr)


# same goes for positive

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]]


# Indexing Slicing

In [ ]:
arr = np.random.randint(1,10 , (2,4))
print(arr)

[[2 5 9 9]
 [9 9 3 6]]


In [ ]:
# indexing
print(arr[1][0])

9


In [ ]:
# Slicing

# 1D array  -> arr[start : end : step]

# 2D array  -> arr[ row_start : row_end : step_for_row , column_start : column_end : step_for_column]


# getting a row

row_0 = arr[0:1 , ]

row_1 = arr[1: , ]


# getting column

column_0 = arr[0: , 0:1]

column_1 = arr[0: , 1:2]

print(column_1)



[[5]
 [9]]


# Advance Indexing and Iteration

In [ ]:
# normal slicing is a view not a copy
# so if i change the view is also change the main array

arr = np.random.randint(1,5,(6,))

arr_slice_copy = arr[1:5]

arr_slice_copy[2]=100

print(arr_slice_copy)
print(arr)

[  2   3 100   1]
[  1   2   3 100   1   3]


In [ ]:
# solve using .copy()

arr = np.random.randint(1,5,(6,))

arr_slice_copy = arr[1:5].copy()

arr_slice_copy[2]=100

print(arr_slice_copy)
print(arr)

[  1   1 100   4]
[4 1 1 2 4 2]


### Advance Indexing

In [ ]:
import numpy as np

arr2 = np.random.randint(1,5,(10))
print(arr)

print(arr2[[1,2,3]])  # duita third bracket


[3 1 4 4 4 4 4 3 4 2]
[2 3 4]


In [ ]:
# 2D array multiple value access

arr3 = np.random.randint(1,5,(5,5))
print(arr3)


print("=="*40)

# element gulor row gulo ekta bracket er moddhe then column gulo arekta brakcet er moddhe majkhane comma

print(arr3[[1,2] , [1,2]])

[[4 4 3 4 1]
 [3 4 2 1 3]
 [4 1 2 1 4]
 [4 4 1 3 2]
 [4 3 4 3 2]]
[4 2]


In [ ]:
# 2 er theke boro value gula amake deo

print(arr3[arr3>2])

print("=="*40)


# 2 er theke boro value gulake zero te convert kore deo

arr3[arr3>2] = 0
print(arr3)

[4 4 3 4 3 4 3 4 4 4 4 3 4 3 4 3]
[[0 0 0 0 1]
 [0 0 2 1 0]
 [0 1 2 1 0]
 [0 0 1 0 2]
 [0 0 0 0 2]]


### Array iteration

In [ ]:
# iteration

for i in arr3 :
  print(i)


print("=="*40)

for i in arr3:
  for j in i :
    print(j , end=" ")

[0 0 0 0 1]
[0 0 2 1 0]
[0 1 2 1 0]
[0 0 1 0 2]
[0 0 0 0 2]
0 0 0 0 1 0 0 2 1 0 0 1 2 1 0 0 0 1 0 2 0 0 0 0 2 

In [ ]:
# Advance iteration

# np.nditer

for i in np.nditer(arr3):
  print(i)

0
0
0
0
1
0
0
2
1
0
0
1
2
1
0
0
0
1
0
2
0
0
0
0
2


In [ ]:
print(np.linspace(0,10,5))

[ 0.   2.5  5.   7.5 10. ]


In [ ]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr[:,1:])

[[20 30]
 [50 60]]


In [ ]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr[:,1])

[20 50]
