In [ ]:
import numpy as np

arr = np.random.randint(1,10,(10,5))

print(arr)

[[8 1 9 3 4]
 [8 2 7 6 4]
 [4 5 6 8 7]
 [2 5 7 2 4]
 [7 7 7 9 9]
 [2 6 4 8 7]
 [9 7 4 8 5]
 [9 1 7 7 7]
 [3 6 5 9 5]
 [8 6 6 8 9]]


In [ ]:
# reshape this into (5,10)

b = arr.reshape(5,10)

print(b)

[[8 1 9 3 4 8 2 7 6 4]
 [4 5 6 8 7 2 5 7 2 4]
 [7 7 7 9 9 2 6 4 8 7]
 [9 7 4 8 5 9 1 7 7 7]
 [3 6 5 9 5 8 6 6 8 9]]


In [ ]:
# flat kore deo

flatten = b.flatten()
print(flatten)
print(flatten.ndim)

[8 1 9 3 4 8 2 7 6 4 4 5 6 8 7 2 5 7 2 4 7 7 7 9 9 2 6 4 8 7 9 7 4 8 5 9 1
 7 7 7 3 6 5 9 5 8 6 6 8 9]
1


In [ ]:
# Flat koro kintu column wise combine koro

column_wise_flattening = np.ravel(b,order='F')

print(column_wise_flattening)

[8 4 7 9 3 1 5 7 7 6 9 6 7 4 5 3 8 9 8 9 4 7 9 5 5 8 2 2 9 8 2 5 6 1 6 7 7
 4 7 6 6 2 8 7 8 4 4 7 7 9]


In [ ]:
a = np.random.randint(1,10, (2,3))
b = np.random.randint(20,30, size = (2,3))

print(a)
print("=="*40)
print(b)


[[4 9 8]
 [2 9 9]]
[[26 22 27]
 [24 29 27]]


# Concatenation

Row wise concatenation -> column same thakte hobe


Column wise concatenation -> row same thakte hobe

In [ ]:
# Axis 0 → vertical direction ↓

# Axis 1 → horizontal direction →

In [ ]:
# Row wise

ans1 = np.concatenate((a,b) , axis =0) # axis 0 -> row wise

print(ans1)

print("=="*40)

# Column Wise

ans2 = np.concatenate((a,b) , axis = 1) # axis 1 -> column wise


print(ans2)

[[ 4  9  8]
 [ 2  9  9]
 [26 22 27]
 [24 29 27]]
[[ 4  9  8 26 22 27]
 [ 2  9  9 24 29 27]]


# Transpose Matrix

In [ ]:
mark = np.random.randint(70,90 , size=(3,3))

print(mark)
print("=="*40)

transpose = mark.T

print(transpose)

[[82 81 83]
 [75 83 87]
 [85 82 80]]
[[82 75 85]
 [81 83 82]
 [83 87 80]]


# Data Split

In [ ]:
# array split

mark = np.random.randint(70,90 , size=(10,))
print(mark)


[81 88 81 88 76 72 88 72 85 71]


In [ ]:
# np.array_split -> number of element same na holeo split kore felbe
# np.split -> number of value same na hole ba equally split na krte parle error show korbe

splitted = np.array_split(mark,3)
print(splitted)



[array([81, 88, 81, 88]), array([76, 72, 88]), array([72, 85, 71])]


In [ ]:
split = np.split(mark,3)
print(split)

ValueError: array split does not result in an equal division

#  ndarray Arithmetic Operators and Mathematical function

### Mathematical operation

In [ ]:
a = np.random.randint(1,10, (2,3))
b = np.random.randint(20,30, size = (2,3))

add = np.add(a,b)
add = a+b # column size must be same
sub = a-b
mul = a*b
div = a/b
remainder = a%b

print(remainder)


[[5 2 2]
 [6 2 9]]


### Trigonometric Operation

In [ ]:
# sin , cos , tab=n , cot all are in radian value

sin_value = np.sin(a)
print(sin_value)
print("=="*40)

# similarly we can find sin cos tan cot all the value

# arcsin , arccos , arctan ..................

# covert radian to degree

deg = np.rad2deg(sin_value)
print(deg)

# similarly deg2rad




[[-0.95892427  0.90929743  0.90929743]
 [-0.2794155   0.90929743  0.41211849]]
[[-54.94231381  52.09890488  52.09890488]
 [-16.00932878  52.09890488  23.61264986]]


### Logaithomic Operation

In [ ]:
base_10_log_val = np.log10(a)

# base 10 mani sonkha ta ke 10 diye koybar vag kora jabe

print(base_10_log_val)
print("=="*40)

dui_diye_kotobat_vag_kora_jabe = np.log2(a)

print(dui_diye_kotobat_vag_kora_jabe)
print("=="*40)


# square root

print(np.sqrt(a))


[[0.69897    0.30103    0.30103   ]
 [0.77815125 0.30103    0.95424251]]
[[2.32192809 1.         1.        ]
 [2.5849625  1.         3.169925  ]]
[[2.23606798 1.41421356 1.41421356]
 [2.44948974 1.41421356 3.        ]]


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])

print(np.sum(a))
print(np.cumsum(a))  # prefix sum

print(np.cumsum(a , axis =1))
print(np.cumsum(a , axis =0))


# np.lcm
# np.gcd



45
[ 1  3  6 10 15 21 28 36 45]


# Numpy Broadcasting

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])

print(a**2)  # sonar sathe kortese
print(a+2)

[ 1  4  9 16 25 36 49 64 81]
[ 3  4  5  6  7  8  9 10 11]


In [ ]:
# For 2D

b = np.array([[1,2,3,4,5,6,7,8,9],
              [1,2,3,4,5,6,7,8,9]
              ])

print(b**2)  # sonar sathe kortese
print(b+2)

[[ 1  4  9 16 25 36 49 64 81]
 [ 1  4  9 16 25 36 49 64 81]]
[[ 3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11]]


# Comparison Operator

In [ ]:
# > < >= <= == !=

a = np.random.randint(1,10, (2,3))
b = np.random.randint(20,30, size = (2,3))

print(a>b)


[[False False False]
 [False False False]]


# Logical Function
## all() -> shob true kina
## any() -> jekono ekta true kina

In [ ]:

print(np.all(b>a))
print(np.all(a>b))


True
False


# Sorting

In [ ]:
# Two kind (Inplace , copy)


# inplace root change

arr = np.array([3,0,71,1,2])

arr.sort()

print(arr)


[ 0  1  2  3 71]


In [ ]:
# Copy sorting

arr = np.array([3,0,71,1,2])

sorted = np.sort(arr)

print(arr)
print(sorted)

[ 3  0 71  1  2]
[ 0  1  2  3 71]


In [ ]:
# Axis 0 → vertical direction ↓

# Axis 1 → horizontal direction →

In [ ]:
# 2D array sorting

import numpy as np

a = np.array([[23, 4, 345],
              [34, 1, 0]])

 # basic = np.sort(a) error asbe axis dite hobe

 # Sorting along axis=0 (column-wise)  vertical direction

col_sort = np.sort(a, axis=0)

row_sort = np.sort(a , axis=1)

print(col_sort)
print("=="*40)
print(row_sort)

[[ 23   1   0]
 [ 34   4 345]]
[[  4  23 345]
 [  0   1  34]]


# Searching

In [ ]:
# np.where(condition , x, y ) if true then x otherwise y

a = np.array([1,2,3,4,5,6,77,34,23,5,6,7,7,75,4,33,3,2,22,2,22])

index = np.where(a==5)
#index = np.where(a>5)

print(index)

index = np.where(a==5 , a , 0) # a thakle a i rakho otherwise change to 0

print(index)

(array([4, 9]),)
[0 0 0 0 5 0 0 0 0 5 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
# 2D array searching

import numpy as np

arr = np.random.randint(1,10,(4,4))
print(arr)


result = np.where(arr>8)

print(result) # first array ta dibe all the row value
              # second array ta dibe all the column value
              # thats why duita array tuple akare dibe


print(arr[1][2])


result = np.where(arr>8 , arr, 0)
print(result)


[[3 6 2 6]
 [1 2 4 8]
 [9 2 5 3]
 [9 5 9 2]]
(array([2, 3, 3]), array([0, 0, 2]))
4
[[0 0 0 0]
 [0 0 0 0]
 [9 0 0 0]
 [9 0 9 0]]


In [ ]:
# Counting

# age hocche matrix take flattern kore then max index ta dey

max_index = np.argmax(arr)
print(max_index)


3


In [ ]:
# this will give row and column both at a time

pos = np.unravel_index(np.argmax(arr), arr.shape)
print(pos)


In [ ]:
import numpy as np
print(np.pi/2)
print(np.sin(np.pi/2))

1.5707963267948966
1.0


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print(np.dot(A,B))

[[19 22]
 [43 50]]
